## Basic Command line Commands
###pwd: For discovering the current directory
*$ pwd
*ls: Show the directory content (cmd-dir rest ls)
*$ ls

###cd: Changing your current directory
*$ cd <path>
*$ cd /Users/Rumil/Downloads (Absolute path)
*$ cd Downloads (Relative path)
*$ cd ~/Downloads (It will take to the right path where ever you are in folder)
*Caution: to visualize only, do not use in scripts (use absolute path only)

###mkdir: Creating directories
*mkdir

###cp : Copying files
*If you want to copy a file into another location type:
*$ cp origin_path destination_path

*If you want to copy a folder into another location type:
*$ cp -r origin_path destination_path
*$ cp -r -f origin_path destination_path (Forcefully… even if no permission)

###mv : Moving files
*Works the same as ‘cp’ but deletes the original file once the new copy is made.
*$ mv origin_path destination_path

###An additional feature is that it works for renaming a file. For instance if in my working directory I have a file called example.txt I want to rename to example2.txt:
*$ mv example.txt example2.txt

###rm: Removing files
*The command that will let us to remove a directory and all its content is
*rm -rf
*-r tells to rm that we want to delete the given directory and all of its contents.
*-f tells to rm that delete the content without prompting for confirmation.

###However be careful by using this command because it can’t be undone.


##First week course notes

*Data science push through obstacles.
*Criticism is part of data science
*Challenge: not enough data/search/surplus data/filter it out. Question should come first… Data later

*Follow on twitter: @bcaffo;@jtleek;@edpeng

*Data deluge: easy to collect, easy to store

*Big data: GPS coordinates, sequence genome,

*Statistical data science: Science of learning data, 

*Lucky: Internet usage; data available in internet; make interesting analysis; High profile results; Prediction & algorithms

*Why R: Wide range of packages, web apps, free, development environment, connecting to developers, easy to install and play around

*Who is data scientist: Daryl Morey- Basketball manager, Hilary Mason-Mining the web,  Daphne Koller-CEO of Coursera,

###Goals: 
*Hacking Skills, Math and Statistics,
*Hacking skills: One-computer programming with R. Second-Ability to go out and answer yourself
*Jobs: Data scientist job is growing faster

###What do data scientist do?
*Define question
*Identify data
*Obtain data
*Clean data
*Exploratory data analysis
*Stats
*Interpret results
*Challenge results
*Write up
*Create reproducible code
*Distribute

###R- Programming language:  R studio (IDE-Integrated Development Environment), 
*Primary type of file: R scripts, functions, R markdown documents-reproduced, repeatable, html files

###Distribution control-Git hub account, commands ran through shell,

###R-programming overview:
*Data types, sub setting, debug , simulations 
###Functions: why are they not working, detailed functions (lapply-arguments, functions) 
###Getting and cleaning data:
###Raw vs tidy data, how to download, how to connect to database, merging data, Raw form of data vs processed data (transforming for analysis)
###Exploratory data analysis:
*Graphics
*Plotting
*Clustering
*Dimension reduction-ggplot 
###Reproducible research:
*Document the work
*Structure
*Organize
*Best practices
*Rpubs-out side organization
###Statistical inference:
*Generalizing information
*Probability
*bootstrap code
###Regression models:
*Communication is key- helped by regression analysis, Regression to mean, Why least square? Equations/calculus.
*Multivariate analysis.
##Machine learning:
*Hands on application in R, mathematical details, 
        				
*TruePositive-Correctly identified	
*TrueNegative-Correctly rejected
*FalsePositive-Incorrectly identified	
*FalseNegative-Incorrectly rejected
				
*Correlated predicted. Basic idea behind boosting
###Building data products:
*What should we do before share it? How to make interactive graphs? Shiny apps...

##Second week course notes

###Git:
*System for version control, runs on command line, helps in keep track of  files and modifications (Repository): runs on local system
###Git hub:
*Web site allows you to upload your repositories ,  It provides backup,  Visual interface for navigating to repose and way to navigate into repose to other people

###What is git?
*Version control system, runs from commond line,can be used alone or in a team

###What is gitHub?
* A website, can not control version, Git repos can be put online, bcking up
##Note: Git doesnot require GitHub

###Advantages of Git/GitHub
*Data scientist write code and version can be controlled, easy to collaborate, Can contribute to open source projetcs, develops your skills.

###Is Git is hard for beginners?
*designed by programmers, Haard to know if I did right, Any actions can have serious consequences, It is command based not workflow focused.

###Git commands
* Cloning repo onto desktop:Bringing repo from Web to local
*git clone <weblink for intended repo>

###Tracking, Commiting and pushing your changes
* git add <NAME>

*For single file:

*git add <file name>

*For all modified and newly created file: use git add period

*git add .

* check which files have been modified/get status

* git status

* Viewing Commiting history

*git log:

*git log -l

*git log -p

*git -p --word-diff

*git --stat

*git --name-status

*git --oneline

*gitk Open a visual commit browser


##Third week course notes

###Types of Question: 
*Framing the questions is key:

*Descriptive: Pattern/trends in the data through Mean, Range, Frequency (Aggregation of data)

*Exploratory: Building relational operations, opinion polls, variations

*Inferential: Exit polls, getting inference from Exploratory data

*Predictive: Modeling….

*Casual: Action to Reaction, casual factor…

*Mechanistic: Machine learning…..

###Big data:
Volume, Velocity, Variety, Verbosity



